<a href="https://colab.research.google.com/github/makhmudjumanazarov/Deep-Learning.AI/blob/main/A_Note_on_Python_Numpy_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

In [3]:
a = np.random.randn(5)

In [4]:
print(a)

[ 0.58415765 -0.89106502  0.00899703 -0.79168137  0.55216957]


In [6]:
print(a.shape)  

(5,)


In [7]:
print(a.T)

[ 0.58415765 -0.89106502  0.00899703 -0.79168137  0.55216957]


In [8]:
print(np.dot(a, a.T))

2.066968619876278


In [10]:
a = np.random.randn(5,1)
print(a)


[[-1.2444371 ]
 [ 0.81173106]
 [-1.4982037 ]
 [-0.41442637]
 [ 0.45906251]]


In [11]:
print(a.T)

[[-1.2444371   0.81173106 -1.4982037  -0.41442637  0.45906251]]


In [12]:
print(np.dot(a, a.T))

[[ 1.54862369 -1.01014824  1.86442027  0.51572755 -0.57127442]
 [-1.01014824  0.65890731 -1.21613847 -0.33640275  0.3726353 ]
 [ 1.86442027 -1.21613847  2.24461433  0.62089512 -0.68776915]
 [ 0.51572755 -0.33640275  0.62089512  0.17174922 -0.19024761]
 [-0.57127442  0.3726353  -0.68776915 -0.19024761  0.21073839]]
